version: "3.8"
services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - SQLALCHEMY_APIS_DATABASE_URI=sqlite:////app/instance/apis.db
      - VALIDATE_USER_PROMPT=true
    volumes:
      - .:/app
      - ./instance:/app/instance # Ensure the database changes persist
      - /var/run/docker.sock:/var/run/docker.sock # Add this line
  code-runner:
    build:
      context: .
      dockerfile: Dockerfile.code-runner
    image: talk2apis-code-runner
