# Use an official Python runtime as a parent image
FROM python:3.8-slim-buster

# Set the working directory in the container to /app
WORKDIR /app

# Install the requests library
RUN pip install --no-cache-dir requests

# This Dockerfile doesn't have a CMD because it will be used to run arbitrary Python scripts