"""Auto-generated migration

Revision ID: 95210e69a5dd
Revises: 84ccdbc5df80
Create Date: 2024-01-25 21:57:33.849195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95210e69a5dd'
down_revision: Union[str, None] = '84ccdbc5df80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_endpoints', sa.Column('embedding', sa.BLOB(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('api_endpoints', 'embedding')
    # ### end Alembic commands ###
